### ISSUE TITLE
Cannot find module 'jasmine2-atom-matchers'

### ISSUE THREAD

**Issue by aminya** [UziTech/atom-jasmine3-test-runner#125]
When I run the tests:
https://github.com/atom-ide-community/atom-ide-template/runs/767583445#step:7:29
```
Installing ./atom
Installing ./attach-to-dom
Installing jasmine2-atom-matchers@^1.1.3
{ Error: Cannot find module 'jasmine2-atom-matchers'
Require stack:
- /home/runner/work/atom-ide-template/atom-ide-template/node_modules/atom-jasmine3-test-runner/lib/spec-helper/spec-helper.js
- /home/runner/work/atom-ide-template/atom-ide-template/node_modules/atom-jasmine3-test-runner/lib/create-runner.js
- /home/runner/work/atom-ide-template/atom-ide-template/node_modules/atom-jasmine3-test-runner/index.js
- /home/runner/work/atom-ide-template/atom-ide-template/spec/runner.js
- /home/runner/work/_temp/atom/usr/share/atom/resources/app.asar/src/initialize-test-window.js
- /home/runner/work/_temp/atom/usr/share/atom/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)

```

**Comment by UziTech** [comment]
If you rerun the action does it still fail?

**Comment by aminya** [comment]
Yes https://github.com/atom-ide-community/atom-ide-template/runs/769356273#step:7:29

**Comment by UziTech** [comment]
Updated version should work
https://github.com/UziTech/atom-jasmine3-test-runner/runs/774980057?check_suite_focus=true#step:7:25

**Comment by aminya** [comment]
This still does not work:
https://github.com/atom-ide-community/atom-ide-javascript/runs/886712114
```ps1
Unable to revert mtime: /usr/share/fonts/type1/gsfonts
Installing ./atom
Installing ./attach-to-dom
Installing jasmine2-atom-matchers@^1.1.4
{ Error: Cannot find module 'jasmine2-atom-matchers'
Require stack:
- /home/runner/work/atom-ide-javascript/atom-ide-javascript/node_modules/atom-jasmine3-test-runner/lib/spec-helper/spec-helper.js
- /home/runner/work/atom-ide-javascript/atom-ide-javascript/node_modules/atom-jasmine3-test-runner/lib/create-runner.js
- /home/runner/work/atom-ide-javascript/atom-ide-javascript/node_modules/atom-jasmine3-test-runner/index.js
- /home/runner/work/atom-ide-javascript/atom-ide-javascript/spec/runner.js
- /home/runner/work/_temp/atom/usr/share/atom/resources/app.asar/src/initialize-test-window.js
- /home/runner/work/_temp/atom/usr/share/atom/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (/home/runner/work/_temp/atom/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._resolveFilename (/home/runner/work/_temp/atom/usr/share/atom/resources/app.asar/src/module-cache.js:336:28)
    at Function.Module._load (internal/modules/cjs/loader.js:601:27)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (/home/runner/work/_temp/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:68:27)
    at /home/runner/work/atom-ide-javascript/atom-ide-javascript/node_modules/atom-jasmine3-test-runner/lib/spec-helper/spec-helper.js:18:3
    at Generator.next (<anonymous>)

```

**Comment by UziTech** [comment]
looks like the node_modules folder was being cached so it wasn't seeing the installed package the first time it tried. This should be fixed in the next release by #135.

**Comment by UziTech** [comment]
it looks like that did fix this issue but caused a different one. 😕
https://github.com/atom-ide-community/atom-ide-template-js/pull/22/checks?check_run_id=888103958#step:7:27

I had to install all of the spec helpers as dependencies and just turn them off by default to fix it.

https://github.com/atom-ide-community/atom-ide-template-js/pull/22

**Comment by aminya** [comment]
Thanks for fixing this. I am totally OK with installing them as dependencies.

P.S: We should not try to circumvent Node issues. The Node itself should solve the problems with dependency management. Like how Deno did.
