### ISSUE TITLE
 The "path" argument must be of type string

### ISSUE THREAD

**Issue by aminya** [UziTech/atom-jasmine3-test-runner#211]
Happens in https://github.com/atom-community/atom-ide-base/pull/47

```js
> atom --test spec
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:372:7)
    at file:///C:/Users/aminy/Documents/GitHub/JavaScript/@atom-ide-community/atom-ide/node_modules/.pnpm/atom-jasmine3-test-runner@5.
1.8/node_modules/atom-jasmine3-test-runner/lib/create-runner.js:137:28
    at Generator.next (<anonymous>)
    at file:///C:/Users/aminy/Documents/GitHub/JavaScript/@atom-ide-community/atom-ide/node_modules/.pnpm/atom-jasmine3-test-runner@5.
1.8/node_modules/atom-jasmine3-test-runner/lib/create-runner.js:290:22
    at Generator.next (<anonymous>)
    at step (file:///C:/Users/aminy/Documents/GitHub/JavaScript/@atom-ide-community/atom-ide/node_modules/.pnpm/atom-jasmine3-test-run
ner@5.1.8/node_modules/atom-jasmine3-test-runner/lib/create-runner.js:82:37)
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  rawStack: [
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {}
  ]
}
```

**Comment by aminya** [comment]
It was caused by atom-package-deps upgrade. The package-deps entry is no longer an array:

```
  testPackages: Array.from(pkg["package-deps"].map(p => p.name)),
```
